In [4]:
import numpy as np 
import tensorflow as tf 
from tensorflow import keras
import pandas as pd 
import matplotlib.pyplot as plt 
%matplotlib inline

In [5]:
df = pd.read_csv("mock_data.csv")
df.head()

,age,affordibility,bought_insurance
0,22,1,0
1,25,0,0
2,47,1,1
3,52,0,0
4,46,1,1


In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df[['age','affordibility']],df.bought_insurance,test_size = 0.2,random_state=25)

In [7]:
x_train_scaled = x_train.copy()
x_train_scaled['age'] = x_train_scaled['age']/100

x_test_scaled = x_test.copy()
x_test_scaled['age'] = x_test_scaled['age']/100

In [8]:
model = keras.Sequential([
    keras.layers.Dense(1, input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])

model.compile(optimizer='adam', loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train_scaled, y_train, epochs=5000)

Epoch 1/5000


d:\Projects\Tensorflow valut\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 498ms/step - accuracy: 0.5238 - loss: 0.6657
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5238 - loss: 0.6654
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5238 - loss: 0.6651
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5238 - loss: 0.6648
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5238 - loss: 0.6645
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5238 - loss: 0.6642
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5238 - loss: 0.6639
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5238 - loss: 0.6636
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5238 - loss: 0.6633
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5238 - loss: 0.6630
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - accuracy: 0.5238 - loss: 0.6628
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5238 - lo

In [9]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 166ms/step - accuracy: 0.8333 - loss: 0.3456


[0.3455779254436493, 0.8333333134651184]

In [10]:
model.predict(x_test_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step


array([[0.7675494 ],
       [0.3960877 ],
       [0.15774845],
       [0.5338377 ],
       [0.7868423 ],
       [0.8781276 ]], dtype=float32)

In [11]:
weights, bias = model.get_weights()
weights, bias

(array([[5.5735126],
        [1.6991647]], dtype=float32),
 array([-3.1241903], dtype=float32))

In [12]:
import sys
import os
project_root = os.path.abspath("..")
sys.path.append(project_root)
from sigmoid_fn import sigmoid

In [13]:
#trying the inference equation
def prediction_fn(age, affordibility):
    y = weights[0]*age + weights[1]*affordibility + bias
    return sigmoid(y) 

In [14]:
prediction_fn(0.47,1)

array([0.76754946], dtype=float32)

In [15]:
from log_loss_fn import log_loss

In [20]:
def gradient_descent(age, affordibility, y_true, epochs, loss_threshold):
    #intialization
    w1=w2=1 
    bias = 0
    learning_rate = 0.1
    n = len(age)

    for i in range(epochs):
        weighted_sum = w1*age + w2*affordibility + bias
        y_predicted = sigmoid(weighted_sum)
        loss = log_loss(y_true, y_predicted)
        w1_d = (1/n)*np.dot((age),(y_predicted - y_true)) 
        w2_d = (1/n)*np.dot((affordibility),(y_predicted - y_true)) 
        bias_d = np.mean(y_predicted-y_true) 
        w1 = w1 - learning_rate*w1_d
        w2 = w2 - learning_rate*w2_d
        bias = bias - learning_rate*bias_d

        print(f"epochs{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}")

        if loss<=loss_threshold:
            break
    return w1,w2,bias        

In [21]:
gradient_descent(x_train_scaled['age'], x_train_scaled['affordibility'], y_train, 1000, 0.4631)

epochs0, w1:0.9965201947766164, w2:0.9930421437721212, bias:-0.0198994720438857, loss:0.6657455469538763
epochs1, w1:0.9932250469009949, w2:0.986360723254102, bias:-0.039328236903887204, loss:0.6612399888169576
epochs2, w1:0.9901116298437153, w2:0.9799522082754322, bias:-0.05829408197237718, loss:0.6569671935888987
epochs3, w1:0.9871768977818154, w2:0.9738128025441972, bias:-0.07680506673734816, loss:0.6529169718804747
epochs4, w1:0.9844176984348333, w2:0.9679384654444813, bias:-0.09486949069551225, loss:0.6490793068434988
epochs5, w1:0.9818307856975989, w2:0.9623249338881185, bias:-0.11249586193758451, loss:0.6454443803942391
epochs6, w1:0.9794128319925703, w2:0.9569677440442502, bias:-0.1296928665826336, loss:0.6420025962816218
epochs7, w1:0.9771604402738441, w2:0.9518622527869577, bias:-0.1464693392148956, loss:0.6387446000580544
epochs8, w1:0.9750701556243401, w2:0.9470036587187041, bias:-0.1628342344531375, loss:0.6356612960440744
epochs9, w1:0.9731384763969037, w2:0.9423870226450

(np.float64(3.560392133463685),
 np.float64(1.6338057456629804),
 np.float64(-2.2886664056211203))